---

- name: deploy portainer-ce latest
  hosts: all
  become: yes
  
  become_user: "{{ lookup('env','USER') }}"
  
  tasks:



  - name: Enable rh-python38
    ansible.builtin.shell: source /opt/rh/rh-python38/enable
    environment:
      PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-python38/root/usr/bin"
    args:
      executable: /bin/bash
    register: enable_result
    changed_when: false  # Mark as unchanged so it doesn't always report a change

  - name: Add source command to ~/.bashrc
    ansible.builtin.lineinfile:
      path: ~/.bashrc
      line: 'source /opt/rh/rh-python38/enable'
      create: yes
  
  - name: Reload ~/.bashrc
    ansible.builtin.shell: source ~/.bashrc
    args:
      executable: /bin/bash
  
  - name: Verify rh-python38 installation
    ansible.builtin.shell: python3 --version
    register: python_version
    changed_when: true
  
  - name: Display Python version
    ansible.builtin.debug:
      var: python_version.stdout_lines

  
  
  - name: create new volume
    community.docker.docker_volume:
      name: portainer-data
  
  - name: deploy portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: unless-stopped
...
